version: "3.9"

services:

  # =========================
  # Django Web Service
  # =========================
  devopsvaultx_web:
    build: .
    container_name: devopsvaultx_app
    restart: always
    env_file:
      - .env
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    depends_on:
      - devopsvaultx_db
    networks:
      - devopsvaultx_network
    command: >
      sh -c "
      python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py collectstatic --noinput &&
      gunicorn devopsvaultx.wsgi:application --bind 0.0.0.0:8000
      "

  # =========================
  # PostgreSQL Database
  # =========================
  devopsvaultx_db:
    image: postgres:15
    container_name: devopsvaultx_db
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - devopsvaultx_network

  # =========================
  # Nginx Reverse Proxy
  # =========================
  devopsvaultx_nginx:
    image: nginx:latest
    container_name: devopsvaultx_nginx_server
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    depends_on:
      - devopsvaultx_web
    networks:
      - devopsvaultx_network

# =========================
# Volumes
# =========================
volumes:
  postgres_data:
  static_volume:
  media_volume:

# =========================
# Networks
# =========================
networks:
  devopsvaultx_network:
