version: "3.9"

services:

  devopsvaultx_web:
    build: .
    container_name: devopsvaultx_app
    restart: always
    env_file:
      - .env
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    depends_on:
      - devopsvaultx_db
    networks:
      - devopsvaultx_network

  devopsvaultx_db:
    image: postgres:15
    container_name: devopsvaultx_db
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    networks:
      - devopsvaultx_network

  devopsvaultx_nginx:
    image: nginx:latest
    container_name: devopsvaultx_nginx_server
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    depends_on:
      - devopsvaultx_web
    networks:
      - devopsvaultx_network

volumes:
  postgres_data:
  static_volume:
  media_volume:

networks:
  devopsvaultx_network:
